### PR TITLE
fix: add precision formatting for tables

### LINKED ISSUE #98: web(fix): Presicion on PhaseTable should be scientific if < E-04

### LINKED ISSUE #99: web(fix): Precision on MoleTable should be 2 decimals

### PR DESCRIPTION
**Pull request by mariuswinger**
## Why is this pull request needed?
Formatting in the tables are currently haywire.

## What does this pull request change?
Table entries are now formatted.

## Issues related to this change:
Closes #98, closes #99

### CODE REVIEW

File: web/src/tableUtils.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+export function formatNumber(
```
Comment (ingeridhellen) [inline web/src/tableUtils.ts:1]: Could you add a docstring on this one? On the format
```suggestion
/**
 *
 * @param {string} param0
 * @returns
 */
export function formatNumber(
```
It is not obvious what the threshold or precision is, and what's their default values

File: web/src/tableUtils.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+  number: number,
+  precision?: number,
+  threshold?: number
+): string {
+  threshold = threshold ? threshold : 4
+  if (number < 10 ** -threshold || number > 10 ** threshold) {
+    return number.toExponential(precision ? precision : 4).replace('e', 'E')
+  } else {
+    return number.toPrecision(precision ? precision : 4).toString()
```
Comment (ingeridhellen) [inline web/src/tableUtils.ts:10]: In JS, you can take default values like this
`function myFunc(myBool: boolean | undefined = true)`
Also, instead of `precision ? precision : 4` you can do `precision ?? 4`, though if you use default values this it not necessary anymore

**Review by ingeridhellen — APPROVED** [review]

File: web/src/tableUtils.ts (hunk 1 above)
Comment (mariuswinger) [reply web/src/tableUtils.ts:1]: Good suggestion. Will do.
