### PR TITLE
fix: added regex check on temp and pressure, disable run button

### LINKED ISSUE #162: fix(web): Disable run button when temp or pressure is "None"

### LINKED ISSUE #250: Fix(web): Limit warnings not shown when writing scientific notation

### PR DESCRIPTION
**Pull request by rikkebl**
## Why is this pull request needed?
Disable run button when invalid input on temperature or pressure.

## What does this pull request change?
Added a regex check and disable run button if input is not valid. 

## Issues related to this change:
closes #162 
closes #250

### CODE REVIEW

File: web/src/feature/calculation_input/TempOrPressureInput.tsx [hunk 1]
```diff
@@ -34,9 +39,14 @@ export const TempOrPressureInput = (props: {
           ? 'The ' + props.name.toLowerCase() + ' is very low'
           : undefined
       }
-      onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
+      onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
+        const regex = /^[-+]?\d+(\.\d+)?([eE][-+]?\d+)?$/
```
Comment (soofstad) [inline web/src/feature/calculation_input/TempOrPressureInput.tsx:43]: Could we add a short description to the regex this?
What it will allow, deny, etc.

**Review by soofstad — APPROVED** [review]
Looks good!
