### PR TITLE
fix: make it possible to input negative numbers

### LINKED ISSUE #104: web: allow negative values to be typed into text field

### PR DESCRIPTION
**Pull request by mariuswinger**
## Why is this pull request needed?

User might have negative values to enter. This was not possible/very hard previously.

## What does this pull request change?

Remove value prop and substitute with placeholder.

## Issues related to this change:
Closes #104

### CODE REVIEW

**Review by soofstad — APPROVED** [review]

File: web/src/components/feature/CalculateFluid.tsx [hunk 1]
```diff
@@ -101,7 +100,7 @@ export const CalculateFluid = ({
             <TextField
               id="temperature-input"
               min={-273.15}
-              value={temperature.toString()}
+              placeholder={temperature.toString()}
```
Comment (ingeridhellen) [inline web/src/components/feature/CalculateFluid.tsx:103]: What about instead doing
```suggestion
              defaultValue={temperature.toString()}
```
?

**Review by ingeridhellen — APPROVED** [review]

File: web/src/components/feature/CalculateFluid.tsx (hunk 1 above)
Comment (mariuswinger) [reply web/src/components/feature/CalculateFluid.tsx:103]: Yes, that is better. Was looking for it, but couldn't find it.
